/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Distillerie: typeof import('./components/Distillerie.vue')['default']
    DistilleryForm: typeof import('./components/DistilleryForm.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Negociant: typeof import('./components/Negociant.vue')['default']
    NegociantForm: typeof import('./components/NegociantForm.vue')['default']
    NegotiantForm: typeof import('./components/NegotiantForm.vue')['default']
    Notation: typeof import('./components/Notation.vue')['default']
    NotationForm: typeof import('./components/NotationForm.vue')['default']
    NotationList: typeof import('./components/NotationList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Whisky: typeof import('./components/Whisky.vue')['default']
    WhiskyForm: typeof import('./components/WhiskyForm.vue')['default']
    WhiskyList: typeof import('./components/WhiskyList.vue')['default']
  }
}
