/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Backup': RouteRecordInfo<'/Backup', '/Backup', Record<never, never>, Record<never, never>>,
    '/Distillerie': RouteRecordInfo<'/Distillerie', '/Distillerie', Record<never, never>, Record<never, never>>,
    '/DistillerieEdit': RouteRecordInfo<'/DistillerieEdit', '/DistillerieEdit', Record<never, never>, Record<never, never>>,
    '/DistillerieList': RouteRecordInfo<'/DistillerieList', '/DistillerieList', Record<never, never>, Record<never, never>>,
    '/Libraries': RouteRecordInfo<'/Libraries', '/Libraries', Record<never, never>, Record<never, never>>,
    '/Negociant': RouteRecordInfo<'/Negociant', '/Negociant', Record<never, never>, Record<never, never>>,
    '/NegociantEdit': RouteRecordInfo<'/NegociantEdit', '/NegociantEdit', Record<never, never>, Record<never, never>>,
    '/NegociantList': RouteRecordInfo<'/NegociantList', '/NegociantList', Record<never, never>, Record<never, never>>,
    '/Whisky': RouteRecordInfo<'/Whisky', '/Whisky', Record<never, never>, Record<never, never>>,
    '/WhiskyEdit': RouteRecordInfo<'/WhiskyEdit', '/WhiskyEdit', Record<never, never>, Record<never, never>>,
  }
}
