"""Init

Revision ID: 01eea5a259e0
Revises: 
Create Date: 2024-12-24 13:31:40.703586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eea5a259e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distillery',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whisky',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('distillery_id', sa.String(), nullable=False),
    sa.Column('negotiant_id', sa.String(), nullable=True),
    sa.Column('alcohol_percentage', sa.Float(), nullable=False),
    sa.Column('whisky_type', sa.String(length=50), nullable=False),
    sa.Column('bottle_size_cl', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_peated', sa.Boolean(), nullable=False),
    sa.Column('nose', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('palate', sa.Text(), nullable=True),
    sa.Column('finish', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['distillery_id'], ['distillery.id'], ),
    sa.ForeignKeyConstraint(['negotiant_id'], ['negotiant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('whisky_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tasting_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['whisky_id'], ['whisky.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasting')
    op.drop_table('whisky')
    op.drop_table('negotiant')
    op.drop_table('distillery')
    # ### end Alembic commands ###
