"""init

Revision ID: 45073f8aa78b
Revises: 
Create Date: 2025-01-02 15:14:40.982011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45073f8aa78b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distillery',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negociant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whisky',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('distillery_id', sa.String(), nullable=False),
    sa.Column('negociant_id', sa.String(), nullable=True),
    sa.Column('alcohol_percentage', sa.Float(), nullable=False),
    sa.Column('whisky_type_id', sa.String(), nullable=False),
    sa.Column('bottle_size_cl', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_peated', sa.Boolean(), nullable=False),
    sa.Column('nose', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('palate', sa.Text(), nullable=True),
    sa.Column('finish', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['distillery_id'], ['distillery.id'], ),
    sa.ForeignKeyConstraint(['negociant_id'], ['negociant.id'], ),
    sa.ForeignKeyConstraint(['whisky_type_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('whisky_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tasting_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['whisky_id'], ['whisky.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasting')
    op.drop_table('whisky')
    op.drop_table('negociant')
    op.drop_table('distillery')
    op.drop_table('library')
    # ### end Alembic commands ###
